================================================================================ test session starts =================================================================================
platform linux -- Python 3.7.2, pytest-4.5.0, py-1.8.0, pluggy-0.9.0
rootdir: /home/ARC/23020/dm_csc_base
plugins: session2file-0.1.9, flake8-1.0.4, xdist-1.29.0, remotedata-0.3.1, openfiles-0.3.2, forked-1.0.2, doctestplus-0.3.0, cov-2.7.1, arraydiff-0.3
collecting ... 
collected 8 items                                                                                                                                                                    

test_base.py FF......                                                                                                                                                          [100%]

====================================================================================== FAILURES ======================================================================================
____________________________________________________________________________ BaseTestCase.test_bad_config ____________________________________________________________________________

self = <lsst.dm.csc.base.base.base object at 0x7f4d71350eb8>, filename = 'config.yaml'

    def loadConfigFile(self, filename):
        """Load configuration file from configuration directory.  The
        default location is $CTRL_IIP_DIR/etc/config.  If the environment
        variable $IIP_CONFIG_DIR exists, files are loaded from that location
        instead.
        """
    
        config_file = filename
    
        if "IIP_CONFIG_DIR" in os.environ:
            config_dir = os.environ["IIP_CONFIG_DIR"]
            config_file = os.path.join(config_dir, config_file)
        else:
            work_dir = f"{self._name}_DIR"
            if work_dir in os.environ:
                config_dir = os.environ[work_dir]
                config_dir = os.path.join(config_dir, "etc", "config")
                config_file = os.path.join(config_dir, config_file)
            else:
                raise Exception(f"environment variable {work_dir} not defined")
    
        print(f"loading {config_file}")
        try:
>           f = open(config_file)
E           FileNotFoundError: [Errno 2] No such file or directory: '/home/ARC/config/config.yaml'

../python/lsst/dm/csc/base/base.py:71: FileNotFoundError

During handling of the above exception, another exception occurred:

self = <test_base.BaseTestCase testMethod=test_bad_config>

    def test_bad_config(self):
        logname = f"test_{os.getpid()}_badconfig.log"
        package = lsst.utils.getPackageDir("dm_csc_base")
        os.environ["test_DIR"] = os.path.join(package, "tests", "files")
        os.environ["IIP_CREDENTIAL_DIR"] = os.path.join(package, "tests", "files")
>       b = base("test", "config.yaml", logname)

test_base.py:80: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../python/lsst/dm/csc/base/base.py:41: in __init__
    self._config = self.loadConfigFile(filename)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <lsst.dm.csc.base.base.base object at 0x7f4d71350eb8>, filename = 'config.yaml'

    def loadConfigFile(self, filename):
        """Load configuration file from configuration directory.  The
        default location is $CTRL_IIP_DIR/etc/config.  If the environment
        variable $IIP_CONFIG_DIR exists, files are loaded from that location
        instead.
        """
    
        config_file = filename
    
        if "IIP_CONFIG_DIR" in os.environ:
            config_dir = os.environ["IIP_CONFIG_DIR"]
            config_file = os.path.join(config_dir, config_file)
        else:
            work_dir = f"{self._name}_DIR"
            if work_dir in os.environ:
                config_dir = os.environ[work_dir]
                config_dir = os.path.join(config_dir, "etc", "config")
                config_file = os.path.join(config_dir, config_file)
            else:
                raise Exception(f"environment variable {work_dir} not defined")
    
        print(f"loading {config_file}")
        try:
            f = open(config_file)
        except Exception:
            msg = f"Can't open {config_file}"
            print(msg)
>           raise FileNotFoundError(msg)
E           FileNotFoundError: Can't open /home/ARC/config/config.yaml

../python/lsst/dm/csc/base/base.py:75: FileNotFoundError
-------------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------------
loading /home/ARC/config/config.yaml
Can't open /home/ARC/config/config.yaml
___________________________________________________________________________ BaseTestCase.test_bad_cred_dir ___________________________________________________________________________

    def loadConfigFile(self, filename):
        """Load configuration file from configuration directory.  The
        default location is $CTRL_IIP_DIR/etc/config.  If the environment
        variable $IIP_CONFIG_DIR exists, files are loaded from that location
        instead.
        """
    
        config_file = filename
    
        if "IIP_CONFIG_DIR" in os.environ:
            config_dir = os.environ["IIP_CONFIG_DIR"]
            config_file = os.path.join(config_dir, config_file)
        else:
            work_dir = f"{self._name}_DIR"
            if work_dir in os.environ:
                config_dir = os.environ[work_dir]
                config_dir = os.path.join(config_dir, "etc", "config")
                config_file = os.path.join(config_dir, config_file)
            else:
                raise Exception(f"environment variable {work_dir} not defined")
    
        print(f"loading {config_file}")
        try:
>           f = open(config_file)
E           FileNotFoundError: [Errno 2] No such file or directory: '/home/ARC/config/config.yaml'

../python/lsst/dm/csc/base/base.py:71: FileNotFoundError

During handling of the above exception, another exception occurred:

self = <test_base.BaseTestCase testMethod=test_bad_cred_dir>

    def test_bad_cred_dir(self):
        logname = f"test_{os.getpid()}_badconfig.log"
        package = lsst.utils.getPackageDir("dm_csc_base")
        os.environ["test_DIR"] = os.path.join(package, "tests", "files")
        os.environ["IIP_CREDENTIAL_DIR"] = os.path.join(package, "tests", "files", "baddir")
        with self.assertRaises(PermissionError):
>           b = base("test", "config.yaml", logname)

test_base.py:99: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../python/lsst/dm/csc/base/base.py:41: in __init__
    self._config = self.loadConfigFile(filename)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def loadConfigFile(self, filename):
        """Load configuration file from configuration directory.  The
        default location is $CTRL_IIP_DIR/etc/config.  If the environment
        variable $IIP_CONFIG_DIR exists, files are loaded from that location
        instead.
        """
    
        config_file = filename
    
        if "IIP_CONFIG_DIR" in os.environ:
            config_dir = os.environ["IIP_CONFIG_DIR"]
            config_file = os.path.join(config_dir, config_file)
        else:
            work_dir = f"{self._name}_DIR"
            if work_dir in os.environ:
                config_dir = os.environ[work_dir]
                config_dir = os.path.join(config_dir, "etc", "config")
                config_file = os.path.join(config_dir, config_file)
            else:
                raise Exception(f"environment variable {work_dir} not defined")
    
        print(f"loading {config_file}")
        try:
            f = open(config_file)
        except Exception:
            msg = f"Can't open {config_file}"
            print(msg)
>           raise FileNotFoundError(msg)
E           FileNotFoundError: Can't open /home/ARC/config/config.yaml

../python/lsst/dm/csc/base/base.py:75: FileNotFoundError
-------------------------------------------------------------------------------- Captured stdout call --------------------------------------------------------------------------------
loading /home/ARC/config/config.yaml
Can't open /home/ARC/config/config.yaml
========================================================================= 2 failed, 6 passed in 0.25 seconds =========================================================================
